services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: private_club_db
    ports:
      - "5432:5432"